### ISSUE TITLE
Can't get it to work... Some more documentation maybe?

### ISSUE THREAD

**Issue by Rinyuu** [Caliel666/DivaModManager#1]
Nice script!

Could you add some more documentation?
I have been trying to get it working on my Steam Deck, but couldn't get it to work.
Tried installing Wine using multiple methods, but none seemed to work.
I'm also not sure what the Wine folder inside .DivaModManager is for.

(I'm a huge noob, so I guess this might have an obvious fix, but I'm sure there are more Linux newcomers that want to run ModManager on Deck like me!)

**Comment by Caliel666** [comment]
this is a very bad script i made and i'm unsure if it works on the deck or not, would like someone to help me test it someday, however the issue might've been related to [this](https://github.com/Caliel666/DivaModManager/issues/2) since the wine folder is supposed to have the wine version used for the app, try pulling the repo again.

as for more documentation, i don't think i need to add more then the basic install instruction, but i do need to work in the script so new linux users can understand it better, and also make it prettier, but basically, run the script, type to install, after a bit it will ask to add a desktop shortcut, and i think this doesn't work on the deck, then you can run the app via my script or add the run script added to `.DivaModManager` into steam

**Comment by Caliel666** [comment]
in the other hand i could provide manual install instructions in the event my script doesn't work, it's actually not that hard of a install process

**Comment by Caliel666** [comment]
yeah the script won't continue until you install .net, you would have to interact with that window, i'm not sure why it's glitched tho

**Comment by Caliel666** [comment]
i wonder if there is a way to install that version of dotnet without a ui

**Comment by Caliel666** [comment]
okay found some info, i will try to update the script i will let you know

**Comment by Rinyuu** [comment]
Thanks a bunch! I'll see if I can get it installed using Winetricks or something similar in the meantime

**Comment by Caliel666** [comment]
you can't, winetricks doesn't install this dotnet version, anyway i pushed a update, check it now

**Comment by Rinyuu** [comment]
You can launch ModManager in Steam by adding the path to DivaModManager.exe and %command% to the launch options for MegaMix.  So in my case it would be D:\Desktop\DivaModManager.exe %command%

As for the script; I tried installing again using the git script, but now I'm having the error you can see in the screenshot I attached
![Screenshot_20220712_175359](https://user-images.githubusercontent.com/37914117/178537554-8294d484-01b5-43eb-a285-07d434441940.png)
.

**Comment by Caliel666** [comment]
that shouldn't work since it requires dotnet 5, unless you install it into the prefix, in my script i have added a run script into the .divamanager folder you can add on steam.

as for the error, looks like you tried to run the manager but you don't have it installed, run install first

**Comment by Rinyuu** [comment]
Hmm, I did run install first. To be sure, I also removed, and then reinstalled after that, but still getting the same error.

**Comment by Caliel666** [comment]
do you have the .divamanager folder ? what's inside of it

**Comment by Caliel666** [comment]
we could also get some logs, open divamodmanager-linux.sh in a text editor and remove line 76 `clear;`, when you run the install it won't delete what it did, send everything to me so i can check what went wrong

**Comment by Rinyuu** [comment]
.divamodmanager folder screenshot and partial log file: I removed clear on line 76, ran the script in Konsole, but it still seemed to delete all activity. Because I already installed before, it asked me to replace, so I had an opportunity to save the script at that point... Hope it helps a little bit.

![Screenshot_20220712_183536](https://user-images.githubusercontent.com/37914117/178547533-25bc0870-2fa1-4192-8cca-f2eb700fdbf3.png)
[log.txt](https://github.com/Caliel666/DivaModManager/files/9095196/log.txt)

**Comment by Caliel666** [comment]
@Rinyuu seems like you are running a older version of the script, delete it and clone the repo again

**Comment by Rinyuu** [comment]
Got it to work! Had to uninstall several times and manually delete all the folders left behind, but then it installed without problems. I can't launch the game through ModManager, but I just added it to steam separately and this works fine :)
